spring:
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:file:.db/accounting-inbox
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
      default_schema: ${application.db.schema}
    show-sql: true